"""Сборка ансамбля запускаемых кейсов и запуск реального симулятора.

Сетка/свойства (`FINAL_GRID.INC`, `FINAL_PROP_PERMX.GRDECL`, ...) могут
весить сотни мегабайт - копировать их на каждую реализацию ансамбля
(десятки-сотни раз) не нужно и не нужно. Вместо этого для каждой
реализации создаётся свой маленький `.DATA` файл - копия исходного с
одной вставленной строкой `INCLUDE` на свой собственный файл
мультипликаторов, а все "тяжёлые" INCLUDE (GRID/PROPS/...) остаются
как в оригинале и продолжают читаться из тех же файлов.

Поэтому кейсы по умолчанию создаются **в той же папке**, где лежит
исходный `.DATA` файл - относительные пути INCLUDE в нём тогда
продолжают работать без изменений. Если нужно писать кейсы в другую
папку, исходный `.DATA` должен использовать только абсолютные пути
INCLUDE.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import numpy as np

from .parameters import ParameterSpace
from .regions import generate_multiplier_include


def _strip_comment(line: str) -> str:
    idx = line.find("--")
    return line if idx == -1 else line[:idx]


def build_case(
    base_data_path: str | Path,
    case_id: int,
    multipliers: dict[int, dict[str, float]],
    dims: tuple[int, int, int],
    out_dir: str | Path | None = None,
    region_keyword: str = "EQLNUM",
    section: str = "EDIT",
    tag: str | None = None,
) -> Path:
    """Создаёт один кейс: `<out_dir>/<base>_caseNNN.DATA` + `..._MULT.INC`.

    Мультипликаторы вставляются как INCLUDE сразу после ключевого слова
    секции `section` (по умолчанию EDIT - пустая секция, которую Petrel
    оставляет специально для таких правок; если у вас её нет, укажите
    например 'GRID'). `tag` (например 'it1') добавляется в имя кейса,
    чтобы кейсы разных итераций ES-MDA не перезаписывали друг друга в
    одной папке. Возвращает путь к .DATA файлу кейса.
    """
    base_data_path = Path(base_data_path)
    out_dir = Path(out_dir) if out_dir is not None else base_data_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    stem = f"{base_data_path.stem}_{tag}" if tag else base_data_path.stem
    case_name = f"{stem}_case{case_id:03d}"
    include_path = out_dir / f"{case_name}_MULT.INC"
    data_path = out_dir / f"{case_name}.DATA"

    generate_multiplier_include(multipliers, dims, include_path, region_keyword)

    lines = base_data_path.read_text(encoding="utf-8", errors="replace").splitlines()
    insert_at = None
    for i, raw_line in enumerate(lines):
        if _strip_comment(raw_line).strip() == section:
            insert_at = i + 1
            break
    if insert_at is None:
        raise ValueError(
            f"Секция {section!r} не найдена в {base_data_path} - укажите существующую "
            "секцию (например 'GRID') параметром section="
        )

    injected = [
        "INCLUDE                                -- Generated by history_match",
        f"  '{include_path.name}' /",
        "",
    ]
    lines[insert_at:insert_at] = injected

    data_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return data_path


def build_ensemble(
    base_data_path: str | Path,
    dims: tuple[int, int, int],
    parameter_space: ParameterSpace,
    log_vectors: np.ndarray,
    out_dir: str | Path | None = None,
    region_keyword: str = "EQLNUM",
    section: str = "EDIT",
    tag: str | None = None,
) -> list[Path]:
    """Строит по одному кейсу на каждый столбец `log_vectors` (n_params, n_ens)."""
    if log_vectors.shape[0] != parameter_space.n_params:
        raise ValueError(
            f"log_vectors должен иметь {parameter_space.n_params} строк, получено {log_vectors.shape[0]}"
        )

    paths = []
    for case_id in range(log_vectors.shape[1]):
        multipliers = parameter_space.to_multiplier_dict(log_vectors[:, case_id])
        paths.append(
            build_case(base_data_path, case_id, multipliers, dims, out_dir, region_keyword, section, tag)
        )
    return paths


def run_case(data_path: str | Path, command: list[str], **subprocess_kwargs) -> subprocess.CompletedProcess:
    """Запускает реальный симулятор на кейсе.

    `command` - шаблон командной строки как список аргументов, где
    элемент `'{deck}'` будет заменён на путь к .DATA файлу кейса,
    например `["eclrun", "eclipse", "{deck}"]` или `["flow", "{deck}"]`
    (для tNavigator/OPM Flow - по документации вашего симулятора).
    Симулятор здесь не эмулируется - это тонкая обёртка над subprocess,
    рассчитанная на запуск на машине, где симулятор реально установлен.
    """
    deck = str(Path(data_path))
    argv = [deck if part == "{deck}" else part for part in command]
    return subprocess.run(argv, capture_output=True, text=True, **subprocess_kwargs)
